import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:image_picker/image_picker.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:local_auth/local_auth.dart';
import 'dart:convert';
import 'dart:typed_data';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: FirebaseOptions(apiKey:"AIzaSyAqhqupsd2veboIOFZfIjaNNOKpKxlV2MI",authDomain:"onyx-movies-2b58b.firebaseapp.com",databaseURL:"https://onyx-movies-2b58b-default-rtdb.firebaseio.com",projectId:"onyx-movies-2b58b",storageBucket:"onyx-movies-2b58b.firebasestorage.app",messagingSenderId:"243702982500",appId:"1:243702982500:web:a65b9c59dd2e06c3ec7c71"));
  runApp(MyApp());
}
class MyApp extends StatefulWidget{const MyApp({super.key});@override State<MyApp> createState()=>MyAppState();}
class MyAppState extends State<MyApp>{
  ThemeMode mode=ThemeMode.dark;
  @override void initState(){super.initState();loadTheme();}
  loadTheme() async {final p=await SharedPreferences.getInstance();setState(()=>mode=(p.getBool('isDark')??true)?ThemeMode.dark:ThemeMode.light);}
  @override Widget build(BuildContext context){return MaterialApp(debugShowCheckedModeBanner:false,themeMode:mode,theme:ThemeData.light(),darkTheme:ThemeData.dark().copyWith(scaffoldBackgroundColor:Color(0xFF020617)),home:AuthScreen(onTheme:(isDark) async {final p=await SharedPreferences.getInstance();await p.setBool('isDark',isDark);setState(()=>mode=isDark?ThemeMode.dark:ThemeMode.light);}));}
}
class AuthScreen extends StatefulWidget{final Function(bool) onTheme;const AuthScreen({super.key,required this.onTheme});@override State<AuthScreen> createState()=>AuthScreenState();}
class AuthScreenState extends State<AuthScreen>{
  final emailC=TextEditingController();final passC=TextEditingController();bool isRegister=true;bool loading=false;bool showPass=false;
  final Map<String,String> adminCreds={"mugabibenjamin14@gmail.com":"Mugabibe+-@1","rachetyaz900@gmail.com":"Akram2007"};
  Future<void> handleAuth() async {
    final email=emailC.text.trim();final pass=passC.text;
    if(email.isEmpty||pass.isEmpty){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("Fill email & password")));return;}
    setState(()=>loading=true);
    final p=await SharedPreferences.getInstance();
    final isAdminEmail=adminCreds.containsKey(email);
    if(isRegister){
      if(isAdminEmail){if(adminCreds[email]!=pass){setState(()=>loading=false);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("Wrong admin password!"),backgroundColor:Colors.red));return;}}
      await p.setString('user_email',email);await p.setString('user_pass',pass);await p.setBool('is_admin',isAdminEmail);
    } else {
      if(isAdminEmail){if(adminCreds[email]!=pass){setState(()=>loading=false);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("Wrong admin password! Access denied"),backgroundColor:Colors.red));return;}await p.setBool('is_admin',true);await p.setString('user_email',email);}
      else {final savedEmail=p.getString('user_email');final savedPass=p.getString('user_pass');if(savedEmail==null){await p.setString('user_email',email);await p.setString('user_pass',pass);await p.setBool('is_admin',false);}else{if(savedEmail!=email||savedPass!=pass){await p.setString('user_email',email);await p.setString('user_pass',pass);await p.setBool('is_admin',false);}}}
    }
    final isAdmin=p.getBool('is_admin')??false;
    setState(()=>loading=false);
    if(mounted){if(isAdmin){Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>StartSelector(onTheme:widget.onTheme,isAdmin:true,email:email)));}else{Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>UserMainNav(onTheme:widget.onTheme,email:email,isAdmin:false)));}}
  }
  @override Widget build(BuildContext context){
    return Scaffold(backgroundColor:Color(0xFF020617),body:SafeArea(child:SingleChildScrollView(padding:EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[SizedBox(height:30),Icon(Icons.movie_filter,color:Color(0xFF38BDF8),size:80),SizedBox(height:12),Text("ONYX MOVIES",style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.bold,letterSpacing:2)),Text(isRegister?"Create Account - Register":"Welcome Back - Login",style:TextStyle(color:Colors.white54,fontSize:14)),SizedBox(height:30),Container(padding:EdgeInsets.all(20),decoration:BoxDecoration(color:Color(0xFF1E293B),borderRadius:BorderRadius.circular(24),border:Border.all(color:Colors.white12)),child:Column(children:[TextField(controller:emailC,decoration:InputDecoration(labelText:"Email",hintText:"Enter email",prefixIcon:Icon(Icons.email,color:Color(0xFF38BDF8)),filled:true,fillColor:Color(0xFF0F172A),border:OutlineInputBorder(borderRadius:BorderRadius.circular(12),borderSide:BorderSide.none)),style:TextStyle(color:Colors.white)),SizedBox(height:12),TextField(controller:passC,obscureText:!showPass,decoration:InputDecoration(labelText:"Password",prefixIcon:Icon(Icons.lock,color:Color(0xFF38BDF8)),suffixIcon:IconButton(icon:Icon(showPass?Icons.visibility:Icons.visibility_off,color:Colors.white54),onPressed:()=>setState(()=>showPass=!showPass)),filled:true,fillColor:Color(0xFF0F172A),border:OutlineInputBorder(borderRadius:BorderRadius.circular(12),borderSide:BorderSide.none)),style:TextStyle(color:Colors.white)),SizedBox(height:20),SizedBox(width:double.infinity,height:50,child:ElevatedButton(onPressed:loading?null:handleAuth,style:ElevatedButton.styleFrom(backgroundColor:Color(0xFF38BDF8),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(12))),child:loading?CircularProgressIndicator(color:Colors.black):Text(isRegister?"REGISTER":"LOGIN",style:TextStyle(color:Colors.black,fontWeight:FontWeight.bold,fontSize:16)))),SizedBox(height:12),TextButton(onPressed:()=>setState(()=>isRegister=!isRegister),child:Text(isRegister?"Already have account? LOGIN":"No account? REGISTER",style:TextStyle(color:Colors.white54))),SizedBox(height:12),Divider(color:Colors.white12),SizedBox(height:8),Text("ADMIN ACCESS ONLY:",style:TextStyle(color:Colors.orange,fontSize:11,fontWeight:FontWeight.bold)),SizedBox(height:4),Text("mugabibenjamin14@gmail.com\nPass: Mugabibe+-@1\n\nrachetyaz900@gmail.com\nPass: Akram2007",style:TextStyle(color:Colors.white24,fontSize:10),textAlign:TextAlign.center)]))]))));
  }
}
class StartSelector extends StatelessWidget{
  final Function(bool) onTheme;final bool isAdmin;final String email;
  const StartSelector({super.key,required this.onTheme,required this.isAdmin,required this.email});
  @override Widget build(BuildContext context){
    return Scaffold(backgroundColor:Color(0xFF020617),appBar:AppBar(backgroundColor:Color(0xFF020617),actions:[IconButton(icon:Icon(Icons.logout,color:Colors.white54),onPressed:() async {final p=await SharedPreferences.getInstance();await p.clear();if(context.mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>AuthScreen(onTheme:onTheme)),(r)=>false);})]),body:SafeArea(child:Padding(padding:EdgeInsets.all(20),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.verified_user,color:Colors.orange,size:50),Text("Welcome Admin",style:TextStyle(color:Colors.orange,fontSize:14)),Text(email,style:TextStyle(color:Colors.white54,fontSize:12)),SizedBox(height:20),Text("ONYX MOVIES",style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.bold)),Text("Choose Panel - Linked",style:TextStyle(color:Colors.white54)),SizedBox(height:40),GestureDetector(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>UserMainNav(onTheme:onTheme,email:email,isAdmin:true))),child:Container(width:double.infinity,height:130,decoration:BoxDecoration(color:Color(0xFF1E293B),borderRadius:BorderRadius.circular(24),border:Border.all(color:Color(0xFF38BDF8),width:2)),child:Row(children:[SizedBox(width:20),Container(width:70,height:70,decoration:BoxDecoration(color:Color(0xFF38BDF8),borderRadius:BorderRadius.circular(18)),child:Icon(Icons.play_circle_fill,color:Colors.black,size:40)),SizedBox(width:20),Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text("USER PANEL",style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.bold)),Text("Home + Movies + Series\n+ Downloads + Profile",style:TextStyle(color:Colors.white54,fontSize:12))]),Spacer(),Icon(Icons.arrow_forward_ios,color:Colors.white54),SizedBox(width:20)]))),SizedBox(height:16),GestureDetector(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AdminMainNav(email:email))),child:Container(width:double.infinity,height:130,decoration:BoxDecoration(color:Color(0xFF1E293B),borderRadius:BorderRadius.circular(24),border:Border.all(color:Colors.orange,width:2)),child:Row(children:[SizedBox(width:20),Container(width:70,height:70,decoration:BoxDecoration(color:Colors.orange,borderRadius:BorderRadius.circular(18)),child:Icon(Icons.admin_panel_settings,color:Colors.black,size:40)),SizedBox(width:20),Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text("ADMIN PANEL",style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.bold)),Text("Add Movie + Banner 1\n+ 5 Casts Circle",style:TextStyle(color:Colors.white54,fontSize:12))]),Spacer(),Icon(Icons.arrow_forward_ios,color:Colors.white54),SizedBox(width:20)]))),SizedBox(height:20),Text("Both panels linked - Same Firebase",style:TextStyle(color:Colors.white24,fontSize:11))]))));
  }
}
class UserMainNav extends StatefulWidget{final Function(bool) onTheme;final String email;final bool isAdmin;const UserMainNav({super.key,required this.onTheme,required this.email,required this.isAdmin});@override State<UserMainNav> createState()=>UserMainNavState();}
class UserMainNavState extends State<UserMainNav>{
  int idx=0;
  @override Widget build(BuildContext context){
    final pages=[HomeExactTab(),MoviesTab(),SeriesTab(),DownloadsTab(),ProfileTab(onTheme:widget.onTheme,email:widget.email,isAdmin:widget.isAdmin)];
    return Scaffold(backgroundColor:Color(0xFF020617),appBar:AppBar(backgroundColor:Color(0xFF020617),leading:widget.isAdmin?IconButton(icon:Icon(Icons.arrow_back,color:Colors.white),onPressed:()=>Navigator.pop(context)):null,title:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(widget.isAdmin?"User Panel (Admin View)":"User Panel",style:TextStyle(color:Colors.white,fontSize:14)),Text(widget.email,style:TextStyle(color:Colors.white54,fontSize:10))]),actions:[IconButton(icon:Icon(Icons.logout,color:Colors.white54),onPressed:() async {final p=await SharedPreferences.getInstance();await p.clear();if(context.mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>AuthScreen(onTheme:widget.onTheme)),(r)=>false);})]),body:pages[idx],bottomNavigationBar:Container(decoration:BoxDecoration(color:Color(0xFF0F172A),border:Border(top:BorderSide(color:Colors.white10))),child:BottomNavigationBar(currentIndex:idx,type:BottomNavigationBarType.fixed,backgroundColor:Color(0xFF0F172A),selectedItemColor:Color(0xFF38BDF8),unselectedItemColor:Colors.white54,onTap:(i)=>setState(()=>idx=i),items:[BottomNavigationBarItem(icon:Icon(Icons.home),label:"Home"),BottomNavigationBarItem(icon:Icon(Icons.movie),label:"Movies"),BottomNavigationBarItem(icon:Icon(Icons.tv),label:"Series"),BottomNavigationBarItem(icon:Icon(Icons.download),label:"Downloads"),BottomNavigationBarItem(icon:Icon(Icons.person),label:"Profile")])));
  }
}
class HomeExactTab extends StatefulWidget{const HomeExactTab({super.key});@override State<HomeExactTab> createState()=>HomeExactTabState();}
class HomeExactTabState extends State<HomeExactTab>{
  final ref=FirebaseDatabase.instance.ref('movies');final bannerRef=FirebaseDatabase.instance.ref('banners');String q="";
  Widget bannerWidget(){return StreamBuilder(stream:bannerRef.onValue,builder:(c,snap){String? b64;if(snap.hasData&&snap.data!.snapshot.value!=null){final map=Map<String,dynamic>.from(snap.data!.snapshot.value as Map);if(map.isNotEmpty){final first=map.entries.first.value;final m=Map<String,dynamic>.from(first as Map);b64=m['imageBase64'];}}return Container(height:200,width:double.infinity,margin:EdgeInsets.symmetric(horizontal:12),decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:LinearGradient(colors:[Color(0xFF3B8DBD),Color(0xFF1E293B)],begin:Alignment.centerLeft,end:Alignment.centerRight),border:Border.all(color:Colors.white12)),child:b64!=null&&b64.length>100?ClipRRect(borderRadius:BorderRadius.circular(24),child:Image.memory(base64Decode(b64.split(',').last),fit:BoxFit.cover)):Center(child:Text("Banner 1 - Upload in Admin",style:TextStyle(color:Colors.white,fontWeight:FontWeight.bold,fontSize:15))));});}
  Widget sectionTitle(String t){return Padding(padding:EdgeInsets.fromLTRB(12,18,12,8),child:Text(t,style:TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.bold)));}
  Widget horizontalList(List<MapEntry> list){return SizedBox(height:160,child:ListView.builder(scrollDirection:Axis.horizontal,padding:EdgeInsets.symmetric(horizontal:12),itemCount:list.length==0?3:list.length,itemBuilder:(c,i){if(list.isEmpty){return Container(width:115,margin:EdgeInsets.only(right:10),decoration:BoxDecoration(color:Color(0xFF1E3A4E),borderRadius:BorderRadius.circular(20),border:Border.all(color:Colors.white12)),child:Center(child:Icon(Icons.movie,color:Colors.white,size:30)));}final m=Map<String,dynamic>.from(list[i].value as Map);final poster=m['posterBase64']??'';return GestureDetector(onTap:(){Navigator.push(c,MaterialPageRoute(builder:(_)=>DetailPage(data:m,id:list[i].key)));},child:Container(width:115,margin:EdgeInsets.only(right:10),decoration:BoxDecoration(color:Color(0xFF1E3A4E),borderRadius:BorderRadius.circular(20),border:Border.all(color:Colors.white12)),child:ClipRRect(borderRadius:BorderRadius.circular(20),child:poster.toString().length>100?Image.memory(base64Decode(poster.toString().split(',').last),fit:BoxFit.cover):Center(child:Icon(Icons.movie,color:Colors.white,size:30)))));})));}
  @override Widget build(BuildContext context){return Column(children:[Padding(padding:EdgeInsets.all(12),child:Row(children:[Expanded(child:Container(height:52,decoration:BoxDecoration(color:Color(0xFF1E293B),borderRadius:BorderRadius.circular(25),border:Border.all(color:Colors.white24)),child:TextField(onChanged:(v)=>setState(()=>q=v.toLowerCase()),style:TextStyle(color:Colors.white),decoration:InputDecoration(hintText:"Search VJ, Genre...",hintStyle:TextStyle(color:Colors.white54),prefixIcon:Icon(Icons.search,color:Color(0xFF38BDF8)),border:InputBorder.none,contentPadding:EdgeInsets.symmetric(vertical:14))))),SizedBox(width:10),Container(height:52,width:52,decoration:BoxDecoration(color:Color(0xFF1E293B),borderRadius:BorderRadius.circular(18),border:Border.all(color:Colors.white24)),child:Icon(Icons.notifications_none,color:Colors.white)) ])),Expanded(child:StreamBuilder(stream:ref.onValue,builder:(c,snap){List<MapEntry> all=[];List<MapEntry> movies=[];List<MapEntry> series=[];if(snap.hasData&&snap.data!.snapshot.value!=null){final map=Map<String,dynamic>.from(snap.data!.snapshot.value as Map);all=map.entries.where((e){final m=Map<String,dynamic>.from(e.value as Map);final t=(m['title']??'').toString().toLowerCase();final vj=(m['vj']??'').toString().toLowerCase();final g=(m['genre']??'').toString().toLowerCase();return t.contains(q)||vj.contains(q)||g.contains(q);}).toList();all.sort((a,b){final ma=Map<String,dynamic>.from(a.value as Map);final mb=Map<String,dynamic>.from(b.value as Map);return (mb['timestamp']??0).compareTo(ma['timestamp']??0);});movies=all.where((e){final m=Map<String,dynamic>.from(e.value as Map);return (m['category']??'Movie').toString().toLowerCase().contains('movie')||!(m['category']??'').toString().toLowerCase().contains('series');}).toList();series=all.where((e){final m=Map<String,dynamic>.from(e.value as Map);return (m['category']??'').toString().toLowerCase().contains('series');}).toList();}return SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[bannerWidget(),sectionTitle("Latest Release"),horizontalList(movies.isEmpty?all:movies),sectionTitle("Latest Series"),horizontalList(series.isEmpty?[]:series),sectionTitle("Trending Movies"),horizontalList(movies.isEmpty?all:movies),SizedBox(height:20)]));}))]);}
}
class MoviesTab extends StatefulWidget{const MoviesTab({super.key});@override State<MoviesTab> createState()=>MoviesTabState();}
class MoviesTabState extends State<MoviesTab>{final ref=FirebaseDatabase.instance.ref('movies');String q="";@override Widget build(BuildContext context){return Column(children:[Padding(padding:EdgeInsets.all(12),child:TextField(onChanged:(v)=>setState(()=>q=v.toLowerCase()),decoration:InputDecoration(hintText:"Search Movies...",prefixIcon:Icon(Icons.search),filled:true,fillColor:Color(0xFF1E293B),border:OutlineInputBorder(borderRadius:BorderRadius.circular(25),borderSide:BorderSide.none)))),Expanded(child:StreamBuilder(stream:ref.onValue,builder:(c,snap){if(!snap.hasData||snap.data!.snapshot.value==null)return Center(child:Text("No Movies",style:TextStyle(color:Colors.white54)));final map=Map<String,dynamic>.from(snap.data!.snapshot.value as Map);final list=map.entries.where((e){final m=Map<String,dynamic>.from(e.value as Map);return (m['category']??'Movie').toString().toLowerCase().contains('movie')||!m['category'].toString().toLowerCase().contains('series');}).where((e){final m=Map<String,dynamic>.from(e.value as Map);return (m['title']??'').toString().toLowerCase().contains(q);}).toList();return GridView.builder(padding:EdgeInsets.all(12),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,childAspectRatio:0.65,crossAxisSpacing:10,mainAxisSpacing:10),itemCount:list.length,itemBuilder:(c,i){final m=Map<String,dynamic>.from(list[i].value as Map);return MovieCard(data:m,id:list[i].key);});}))]);}}
class SeriesTab extends StatefulWidget{const SeriesTab({super.key});@override State<SeriesTab> createState()=>SeriesTabState();}
class SeriesTabState extends State<SeriesTab>{final ref=FirebaseDatabase.instance.ref('movies');String q="";@override Widget build(BuildContext context){return Column(children:[Padding(padding:EdgeInsets.all(12),child:TextField(onChanged:(v)=>setState(()=>q=v.toLowerCase()),decoration:InputDecoration(hintText:"Search Series...",prefixIcon:Icon(Icons.search),filled:true,fillColor:Color(0xFF1E293B),border:OutlineInputBorder(borderRadius:BorderRadius.circular(25),borderSide:BorderSide.none)))),Expanded(child:StreamBuilder(stream:ref.onValue,builder:(c,snap){if(!snap.hasData||snap.data!.snapshot.value==null)return Center(child:Text("No Series",style:TextStyle(color:Colors.white54)));final map=Map<String,dynamic>.from(snap.data!.snapshot.value as Map);final list=map.entries.where((e){final m=Map<String,dynamic>.from(e.value as Map);return (m['category']??'').toString().toLowerCase().contains('series');}).where((e){final m=Map<String,dynamic>.from(e.value as Map);return (m['title']??'').toString().toLowerCase().contains(q);}).toList();return GridView.builder(padding:EdgeInsets.all(12),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,childAspectRatio:0.65,crossAxisSpacing:10,mainAxisSpacing:10),itemCount:list.length,itemBuilder:(c,i){final m=Map<String,dynamic>.from(list[i].value as Map);return MovieCard(data:m,id:list[i].key);});}))]);}}
class MovieCard extends StatelessWidget{final Map<String,dynamic> data;final String id;const MovieCard({super.key,required this.data,required this.id});@override Widget build(BuildContext context){final poster=data['posterBase64']??'';return GestureDetector(onTap:(){Navigator.push(context,MaterialPageRoute(builder:(_)=>DetailPage(data:data,id:id)));},child:Container(decoration:BoxDecoration(color:Color(0xFF1E293B),borderRadius:BorderRadius.circular(16)),child:Column(children:[Expanded(child:ClipRRect(borderRadius:BorderRadius.vertical(top:Radius.circular(16)),child:poster.toString().length>100?Image.memory(base64Decode(poster.toString().split(',').last),fit:BoxFit.cover,width:double.infinity):Container(color:Color(0xFF1E3A4E),child:Center(child:Icon(Icons.movie,color:Colors.white))))),Padding(padding:EdgeInsets.all(6),child:Text(data['title']??'No Title',maxLines:1,style:TextStyle(color:Colors.white,fontWeight:FontWeight.bold,fontSize:11)))])));}}
class DetailPage extends StatelessWidget{final Map<String,dynamic> data;final String id;const DetailPage({super.key,required this.data,required this.id});@override Widget build(BuildContext context){final casts=data['casts'] is List?data['casts'] as List:[];return Scaffold(backgroundColor:Color(0xFF020617),appBar:AppBar(backgroundColor:Color(0xFF020617),title:Text(data['title']??'')),body:SingleChildScrollView(padding:EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[ClipRRect(borderRadius:BorderRadius.circular(16),child:AspectRatio(aspectRatio:16/9,child:Container(color:Color(0xFF1E293B),child:Icon(Icons.play_circle,size:60,color:Colors.white54)))),SizedBox(height:12),Text(data['title']??'',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold,color:Colors.white)),Text("${data['vj']??''} • ${data['genre']??''} • ${data['category']??'Movie'}",style:TextStyle(color:Colors.white54)),SizedBox(height:12),Text("Casts (5 max - Circle)",style:TextStyle(fontSize:16,fontWeight:FontWeight.bold,color:Colors.white)),SizedBox(height:8),casts.isEmpty?Text("No casts",style:TextStyle(color:Colors.white54)):SizedBox(height:110,child:ListView.builder(scrollDirection:Axis.horizontal,itemCount:casts.length>5?5:casts.length,itemBuilder:(c,i){final cast=Map<String,dynamic>.from(casts[i] as Map);final img=cast['imageBase64']??'';return Container(width:75,margin:EdgeInsets.only(right:10),child:Column(children:[CircleAvatar(radius:28,backgroundColor:Color(0xFF1E293B),backgroundImage:img.toString().length>100?MemoryImage(base64Decode(img.toString().split(',').last)):null,child:img.toString().length<100?Icon(Icons.person):null),SizedBox(height:4),Text(cast['realName']??'',maxLines:1,style:TextStyle(fontSize:10,color:Colors.white,fontWeight:FontWeight.bold)),Text("as ${cast['actedName']??''}",maxLines:1,style:TextStyle(fontSize:9,color:Colors.white54))])) ;})),SizedBox(height:12),Text(data['description']??'No description',style:TextStyle(color:Colors.white70))])));}}
class DownloadsTab extends StatefulWidget{const DownloadsTab({super.key});@override State<DownloadsTab> createState()=>DownloadsTabState();}
class DownloadsTabState extends State<DownloadsTab> with SingleTickerProviderStateMixin{
  late TabController tab;
  @override void initState(){super.initState();tab=TabController(length:2,vsync:this);}
  @override Widget build(BuildContext context){
    return Column(children:[
      Container(margin:EdgeInsets.all(12),padding:EdgeInsets.all(12),decoration:BoxDecoration(color:Color(0xFF1E293B),borderRadius:BorderRadius.circular(12)),child:Row(children:[Icon(Icons.storage,color:Color(0xFF38BDF8)),SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text("Used: 3.2GB / 15.7GB",style:TextStyle(color:Colors.white,fontSize:12)),SizedBox(height:4),LinearProgressIndicator(value:0.2,backgroundColor:Colors.white12,color:Color(0xFF38BDF8)),SizedBox(height:4),Text("Free: 12.5GB available",style:TextStyle(color:Colors.white54,fontSize:10))]))])),
      TabBar(controller:tab,labelColor:Color(0xFF38BDF8),unselectedLabelColor:Colors.white54,tabs:[Tab(text:"Downloading"),Tab(text:"Completed")]),
      Expanded(child:TabBarView(controller:tab,children:[Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.downloading,size:80,color:Colors.white24),Text("No active downloads",style:TextStyle(color:Colors.white54))])),Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.download_done,size:80,color:Colors.white24),Text("No available download",style:TextStyle(color:Colors.white54))]))])),
    ]);
  }
}
class ProfileTab extends StatefulWidget{final Function(bool) onTheme;final String email;final bool isAdmin;const ProfileTab({super.key,required this.onTheme,required this.email,required this.isAdmin});@override State<ProfileTab> createState()=>ProfileTabState();}
class ProfileTabState extends State<ProfileTab>{
  bool isDark=true;bool galleryMode=true;final picker=ImagePicker();Uint8List? avatarBytes;
  Future<void> pickAvatar() async {final x=await picker.pickImage(source:ImageSource.gallery);if(x!=null){final b=await x.readAsBytes();setState(()=>avatarBytes=b);final p=await SharedPreferences.getInstance();await p.setString('avatar',base64Encode(b));}}
  @override void initState(){super.initState();loadData();}
  loadData() async {final p=await SharedPreferences.getInstance();setState((){isDark=p.getBool('isDark')??true;galleryMode=p.getBool('galleryMode')??true;});final av=p.getString('avatar');if(av!=null)setState(()=>avatarBytes=base64Decode(av));}
  @override Widget build(BuildContext context){
    return ListView(padding:EdgeInsets.all(12),children:[
      Center(child:GestureDetector(onTap:pickAvatar,child:CircleAvatar(radius:45,backgroundColor:Color(0xFF1E293B),backgroundImage:avatarBytes!=null?MemoryImage(avatarBytes!):null,child:avatarBytes==null?Icon(Icons.person,size:40):null))),
      SizedBox(height:8),Center(child:Text(widget.email,style:TextStyle(color:Colors.white,fontWeight:FontWeight.bold))),Center(child:Text(widget.isAdmin?"ADMIN ACCESS":"USER",style:TextStyle(color:widget.isAdmin?Colors.orange:Color(0xFF38BDF8),fontSize:12,fontWeight:FontWeight.bold))),Center(child:Text("Tap to change avatar from Gallery",style:TextStyle(color:Colors.white54,fontSize:11))),
      SizedBox(height:20),
      if(widget.isAdmin) Container(decoration:BoxDecoration(color:Colors.orange,borderRadius:BorderRadius.circular(12)),child:ListTile(leading:Icon(Icons.admin_panel_settings,color:Colors.black),title:Text("Go to ADMIN PANEL",style:TextStyle(color:Colors.black,fontWeight:FontWeight.bold)),subtitle:Text("Add Movie + Banner 1 - Admin only",style:TextStyle(color:Colors.black54,fontSize:11)),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AdminMainNav(email:widget.email))))),
      if(widget.isAdmin) SizedBox(height:12),
      ListTile(title:Text("Theme Dark"),trailing:Switch(value:isDark,onChanged:(v) async {setState(()=>isDark=v);widget.onTheme(v);final p=await SharedPreferences.getInstance();await p.setBool('isDark',v);})),
      ListTile(title:Text("Gallery Mode Switch"),trailing:Switch(value:galleryMode,onChanged:(v) async {setState(()=>galleryMode=v);final p=await SharedPreferences.getInstance();await p.setBool('galleryMode',v);})),
      Divider(color:Colors.white12),
      ListTile(leading:Icon(Icons.download,color:Color(0xFF38BDF8)),title:Text("Download Latest & Install"),subtitle:Text("Get V1.1.0 APK from Releases",style:TextStyle(fontSize:12,color:Colors.white54)),onTap:() async {final uri=Uri.parse("https://github.com/bluezzer/onyx-movie-final/releases");if(await canLaunchUrl(uri))await launchUrl(uri,mode:LaunchMode.externalApplication);}),
      ListTile(leading:Icon(Icons.security,color:Color(0xFF38BDF8)),title:Text("Security - Biometric"),subtitle:Text("Fingerprint lock",style:TextStyle(fontSize:12,color:Colors.white54)),onTap:() async {final auth=LocalAuthentication();final can=await auth.canCheckBiometrics;if(can){final did=await auth.authenticate(localizedReason:"Authenticate to open ONYX");if(did&&mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("Authenticated")));}}),
      ListTile(leading:Icon(Icons.contact_mail,color:Color(0xFF38BDF8)),title:Text("Contact Us"),onTap:() async {final uri=Uri.parse("mailto:support@onyxmovies.com");if(await canLaunchUrl(uri))await launchUrl(uri);}),
      ListTile(leading:Icon(Icons.app_registration,color:Color(0xFF38BDF8)),title:Text("Register New Account"),onTap:(){showDialog(context:context,builder:(_)=>AlertDialog(title:Text("Register"),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(decoration:InputDecoration(labelText:"Email")),TextField(decoration:InputDecoration(labelText:"Password"),obscureText:true)]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:Text("Sign Up"))]));}),
      ListTile(leading:Icon(Icons.logout,color:Colors.red),title:Text("Logout",style:TextStyle(color:Colors.red)),onTap:() async {final p=await SharedPreferences.getInstance();await p.clear();if(context.mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>AuthScreen(onTheme:widget.onTheme)),(r)=>false);}),
    ]);
  }
}
class AdminMainNav extends StatefulWidget{final String email;const AdminMainNav({super.key,required this.email});@override State<AdminMainNav> createState()=>AdminMainNavState();}
class AdminMainNavState extends State<AdminMainNav>{
  int idx=0;
  @override Widget build(BuildContext context){
    final pages=[AdminDashboardTab(email:widget.email),AdminAddMovie(),AdminManageMovies()];
    return Scaffold(backgroundColor:Color(0xFF020617),appBar:AppBar(backgroundColor:Color(0xFF020617),title:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text("ADMIN PANEL",style:TextStyle(color:Colors.orange,fontWeight:FontWeight.bold,fontSize:16)),Text(widget.email,style:TextStyle(color:Colors.white54,fontSize:10))]),iconTheme:IconThemeData(color:Colors.white),actions:[IconButton(icon:Icon(Icons.logout,color:Colors.white54),onPressed:() async {final p=await SharedPreferences.getInstance();await p.clear();if(context.mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>AuthScreen(onTheme:(v) async {})),(r)=>false);})]),body:pages[idx],bottomNavigationBar:BottomNavigationBar(currentIndex:idx,type:BottomNavigationBarType.fixed,backgroundColor:Color(0xFF0F172A),selectedItemColor:Colors.orange,unselectedItemColor:Colors.white54,onTap:(i)=>setState(()=>idx=i),items:[BottomNavigationBarItem(icon:Icon(Icons.dashboard),label:"Dashboard"),BottomNavigationBarItem(icon:Icon(Icons.add_box),label:"Add Movie"),BottomNavigationBarItem(icon:Icon(Icons.list),label:"Manage")]));
  }
}
class AdminDashboardTab extends StatelessWidget{
  final String email;
  const AdminDashboardTab({super.key,required this.email});
  @override Widget build(BuildContext context){
    final ref=FirebaseDatabase.instance.ref('movies');
    return StreamBuilder(stream:ref.onValue,builder:(c,snap){
      int count=0;
      if(snap.hasData&&snap.data!.snapshot.value!=null){final map=Map<String,dynamic>.from(snap.data!.snapshot.value as Map);count=map.length;}
      return ListView(padding:EdgeInsets.all(16),children:[
        Container(padding:EdgeInsets.all(20),decoration:BoxDecoration(color:Color(0xFF1E293B),borderRadius:BorderRadius.circular(16)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text("Admin Dashboard",style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.bold)),Text("Logged as: $email",style:TextStyle(color:Colors.orange,fontSize:12)),SizedBox(height:10),Row(children:[Icon(Icons.movie,color:Colors.orange),SizedBox(width:8),Text("Total Movies/Series: $count",style:TextStyle(color:Colors.white))]),SizedBox(height:8),Row(children:[Icon(Icons.storage,color:Color(0xFF38BDF8)),SizedBox(width:8),Text("Storage Used: 3.2GB / 15.7GB",style:TextStyle(color:Colors.white54,fontSize:12))]),SizedBox(height:8),Row(children:[Icon(Icons.sd_storage,color:Colors.green),SizedBox(width:8),Text("Free: 12.5GB available",style:TextStyle(color:Colors.green,fontSize:12))])])),
        SizedBox(height:16),
        Container(decoration:BoxDecoration(color:Colors.orange,borderRadius:BorderRadius.circular(12)),child:ListTile(leading:Icon(Icons.add_photo_alternate,color:Colors.black),title:Text("Add Banner 1",style:TextStyle(color:Colors.black,fontWeight:FontWeight.bold)),subtitle:Text("Banner shows on User Home exact",style:TextStyle(color:Colors.black54,fontSize:11)),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AdminAddMovie())))),
        SizedBox(height:10),
        Container(decoration:BoxDecoration(color:Color(0xFF38BDF8),borderRadius:BorderRadius.circular(12)),child:ListTile(leading:Icon(Icons.add_box,color:Colors.black),title:Text("Add Movie + 5 Casts Circle",style:TextStyle(color:Colors.black,fontWeight:FontWeight.bold)),subtitle:Text("Gallery poster + banner + casts",style:TextStyle(color:Colors.black54,fontSize:11)),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AdminAddMovie())))),
        SizedBox(height:10),
        Container(decoration:BoxDecoration(color:Color(0xFF1E293B),borderRadius:BorderRadius.circular(12),border:Border.all(color:Colors.white12)),child:ListTile(leading:Icon(Icons.people,color:Colors.white),title:Text("User Panel Control",style:TextStyle(color:Colors.white,fontWeight:FontWeight.bold)),subtitle:Text("View how users see app",style:TextStyle(color:Colors.white54,fontSize:11)),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>UserMainNav(onTheme:(v) async {},email:email,isAdmin:true))))),
      ]);
    });
  }
}
class AdminManageMovies extends StatefulWidget{const AdminManageMovies({super.key});@override State<AdminManageMovies> createState()=>AdminManageMoviesState();}
class AdminManageMoviesState extends State<AdminManageMovies>{
  final ref=FirebaseDatabase.instance.ref('movies');
  @override Widget build(BuildContext context){
    return StreamBuilder(stream:ref.onValue,builder:(c,snap){
      if(!snap.hasData||snap.data!.snapshot.value==null)return Center(child:Text("No movies yet - Add in Admin",style:TextStyle(color:Colors.white54)));
      final map=Map<String,dynamic>.from(snap.data!.snapshot.value as Map);
      final list=map.entries.toList();
      return ListView.builder(padding:EdgeInsets.all(12),itemCount:list.length,itemBuilder:(c,i){
        final m=Map<String,dynamic>.from(list[i].value as Map);
        return Card(color:Color(0xFF1E293B),child:ListTile(leading:Icon(Icons.movie,color:Colors.orange),title:Text(m['title']??'',style:TextStyle(color:Colors.white,fontWeight:FontWeight.bold)),subtitle:Text("${m['category']??''} • ${m['vj']??''} • ${m['genre']??''}\nCasts: ${(m['casts'] is List)?(m['casts'] as List).length:0}",style:TextStyle(color:Colors.white54,fontSize:11)),isThreeLine:true,trailing:IconButton(icon:Icon(Icons.delete,color:Colors.red),onPressed:() async {await ref.child(list[i].key).remove();ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("Deleted")));})));
      });
    });
  }
}
class AdminAddMovie extends StatefulWidget{const AdminAddMovie({super.key});@override State<AdminAddMovie> createState()=>AdminAddMovieState();}
class AdminAddMovieState extends State<AdminAddMovie>{
  final titleC=TextEditingController();final descC=TextEditingController();final vjC=TextEditingController(text:"VJ Junior");final genreC=TextEditingController(text:"Action");String category="Movie";final picker=ImagePicker();Uint8List? posterBytes;Uint8List? bannerBytes;List<Map<String,dynamic>> casts=[];
  pickPoster() async {final x=await picker.pickImage(source:ImageSource.gallery);if(x!=null){final b=await x.readAsBytes();setState(()=>posterBytes=b);}}
  pickBanner() async {final x=await picker.pickImage(source:ImageSource.gallery);if(x!=null){final b=await x.readAsBytes();setState(()=>bannerBytes=b);}}
  addCast() async {
    if(casts.length>=5){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("Max 5 casts")));return;}
    final realC=TextEditingController();final actedC=TextEditingController();Uint8List? castImg;
    await showDialog(context:context,builder:(_)=>StatefulBuilder(builder:(c,setS)=>AlertDialog(title:Text("Add Cast Circle"),content:Column(mainAxisSize:MainAxisSize.min,children:[GestureDetector(onTap:() async {final x=await picker.pickImage(source:ImageSource.gallery);if(x!=null){final b=await x.readAsBytes();setS(()=>castImg=b);}},child:CircleAvatar(radius:30,backgroundImage:castImg!=null?MemoryImage(castImg!):null,child:castImg==null?Icon(Icons.person):null)),SizedBox(height:8),Text("Pick cast image from Gallery",style:TextStyle(fontSize:10,color:Colors.grey)),TextField(controller:realC,decoration:InputDecoration(labelText:"Real Name")),TextField(controller:actedC,decoration:InputDecoration(labelText:"Acted Name (as)"))]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:Text("Cancel")),TextButton(onPressed:(){setState(()=>casts.add({"realName":realC.text,"actedName":actedC.text,"imageBase64":castImg!=null?base64Encode(castImg!):""}));Navigator.pop(context);},child:Text("Add"))])));
  }
  save() async {
    if(titleC.text.isEmpty){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("Title required")));return;}
    if(bannerBytes!=null){final bRef=FirebaseDatabase.instance.ref('banners').push();await bRef.set({"imageBase64":base64Encode(bannerBytes!),"timestamp":DateTime.now().millisecondsSinceEpoch});}
    final ref=FirebaseDatabase.instance.ref('movies').push();
    await ref.set({"title":titleC.text,"description":descC.text,"vj":vjC.text,"genre":genreC.text,"category":category,"posterBase64":posterBytes!=null?base64Encode(posterBytes!):"","bannerBase64":bannerBytes!=null?base64Encode(bannerBytes!):"","casts":casts,"timestamp":DateTime.now().millisecondsSinceEpoch});
    if(mounted){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("Saved! Shows in USER panel instantly")));Navigator.pop(context);}
  }
  @override Widget build(BuildContext context){
    return Scaffold(appBar:AppBar(title:Text("ADMIN: Add Movie + Banner 1 + 5 Casts")),body:SingleChildScrollView(padding:EdgeInsets.all(12),child:Column(children:[TextField(controller:titleC,decoration:InputDecoration(labelText:"Movie Title *")),TextField(controller:descC,decoration:InputDecoration(labelText:"Description")),TextField(controller:vjC,decoration:InputDecoration(labelText:"VJ Name")),TextField(controller:genreC,decoration:InputDecoration(labelText:"Genre")),SizedBox(height:12),Row(children:[Text("Category:"),SizedBox(width:10),DropdownButton<String>(value:category,items:["Movie","Series"].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v)=>setState(()=>category=v!))]),SizedBox(height:12),Row(children:[Expanded(child:ElevatedButton.icon(onPressed:pickPoster,icon:Icon(Icons.image),label:Text(posterBytes==null?"Pick Poster\nGallery":"Poster OK"))),SizedBox(width:8),Expanded(child:ElevatedButton.icon(onPressed:pickBanner,icon:Icon(Icons.panorama),label:Text(bannerBytes==null?"Pick Banner 1\nGallery":"Banner OK")))]),SizedBox(height:12),Row(children:[Text("Casts (max 5 - Circle)"),Spacer(),ElevatedButton(onPressed:addCast,child:Text("Add Cast"))]),SizedBox(height:8),Text("Pick cast image + real name + acted name",style:TextStyle(color:Colors.white54,fontSize:10)),SizedBox(height:4),Wrap(spacing:8,children:casts.map((c)=>Chip(avatar:CircleAvatar(child:Text(c['realName'].toString().isNotEmpty?c['realName'][0]:"?")),label:Text(c['realName']))).toList()),SizedBox(height:20),SizedBox(width:double.infinity,height:50,child:ElevatedButton(onPressed:save,style:ElevatedButton.styleFrom(backgroundColor:Colors.orange),child:Text("Save to Firebase - Linked to User",style:TextStyle(color:Colors.black,fontWeight:FontWeight.bold))))])));
  }
}
